= 50 Algorithms every Programmer must know (Packt Publishing)
Aadvik <aadv1k@outlook.com>

:stem: latexmath

An algorithm is a set of finite, unambiguous deterministic instructions, that with the correct starting conditions can produce a desired output


An algorithm may operate under one of 3 cases :- 

* *Worst-Case Scenario* in this case each execution step doesn't or actively deters the algorithm from completion. This occurs due to bad end-conditions or runaway recursions.
* *Best-Case Scenario*: where each execution step gets the algorithm closer to the desired output
* *Average-Case Scenratio*: the execution steps don't do much at all

[source, python]
----

"""
- Worst: Reversed data, need to check every element O(n^2)
- Best: Partially sorted data O(n)
- Average: already sorted data O(n)
"""

def insertion_sort(s):
    for i in range(1, len(s)):
        cur, j = s[i], i

        while j > 0 and s[j-1] > cur:
            s[j] = s[j-1]
            j -= 1

        s[j] = cur
----

== Polynomials and Non-Deterministic Polynomials

* *Polynomial Algorithm* is an algorithm that runs in polynomial time, which is latexmath:[O(N^k)] time. These kinds execute in a "reasonable" time, unlike exponetial algorithms. 
* *Non-Deterministic Polynomials* algorithms for which a "check" which can run in polynomial time exists, to validate their correctness.
* *P = NP cojecture* it can be proven that latexmath:[P \subseteq NP] however, can we say for every algorithm which can be validated in P time there exists a solution also in P time? this is unproven.
* *NP-Hard and NP-Complete* NP-Hard problems are those for which neither a check, nor a solution exists (at-least in polynomial time), *NP-Complete* are problems, for which if a proof can be found out, it can be proven latexmath:[P = NP]

== Algorithmic Strategies

* *Divide and Conquer* break a problem `P` down into `k` chunks, and provide `k` piece of dataset to each chunk to compute.
* *Greedy* approach in which only the first possible solution is found, even if it might not be the most optimial. _if problem is to find a train, departing on time X, then greedy approach will return the first train departing on T < X_
